import fs from 'node:fs';
import path from 'node:path';

const appRoot = path.resolve(import.meta.dirname, '..');
const srcRoot = path.join(appRoot, 'src');
const distRoot = path.join(appRoot, 'dist');
const entryFile = path.join(srcRoot, 'index.js');

fs.mkdirSync(distRoot, { recursive: true });

const packageJson = JSON.parse(fs.readFileSync(path.join(appRoot, 'package.json'), 'utf8'));
const graph = buildModuleGraph(entryFile);
const bundle = renderBundle(graph, moduleId(entryFile));

const css = [
    '.igs-stage { position: relative; width: 100%; height: 100%; min-height: 320px; overflow: hidden; background: #0b0d12; }',
    '.igs-background-layer, .igs-generated-layer, .igs-effect-layer, .igs-character-layer, .igs-avatar-layer, .igs-dialogue-layer, .igs-hud-layer, .igs-choice-layer, .igs-system-layer { position: absolute; inset: 0; }',
    '.igs-dialogue-layer { left: 0; right: 0; bottom: 0; width: 100%; min-height: 96px; padding: 24px; }',
    '.igs-toolbar { display: flex; gap: 8px; padding: 6px; border-radius: 8px; }',
    '',
].join('\n');

const manifest = {
    name: 'immersive-galgame-system',
    version: packageJson.version,
    entry: 'igs.bundle.js',
    style: 'igs.bundle.css',
};

fs.writeFileSync(path.join(distRoot, 'igs.bundle.js'), bundle, 'utf8');
fs.writeFileSync(path.join(distRoot, 'igs.bundle.css'), css, 'utf8');
fs.writeFileSync(path.join(distRoot, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

for (const name of ['igs.bundle.js', 'igs.bundle.css', 'manifest.json']) {
    const file = path.join(distRoot, name);
    if (!fs.existsSync(file) || fs.statSync(file).size === 0) {
        throw new Error(`Build output is missing or empty: ${name}`);
    }
}

const builtBundle = fs.readFileSync(path.join(distRoot, 'igs.bundle.js'), 'utf8');
if (/^\s*import\s/m.test(builtBundle) || builtBundle.includes("from '../src/index.js'")) {
    throw new Error('Build output must be self-contained and must not import app/src modules at runtime.');
}

console.log('gate:build ok');

function buildModuleGraph(rootFile) {
    const modules = new Map();
    visit(rootFile);
    return modules;

    function visit(file) {
        const absolute = path.resolve(file);
        const id = moduleId(absolute);
        if (modules.has(id)) return;
        const source = fs.readFileSync(absolute, 'utf8');
        const dependencies = extractDependencies(source).map((request) => resolveLocalModule(absolute, request));
        modules.set(id, { id, file: absolute, source, dependencies });
        for (const dependency of dependencies) {
            visit(dependency.file);
        }
    }
}

function renderBundle(graph, entryId) {
    const transformed = [];
    let entryExports = [];
    for (const module of graph.values()) {
        const result = transformModule(module);
        if (module.id === entryId) entryExports = result.exportNames;
        transformed.push([
            `__igsRegister(${JSON.stringify(module.id)}, function(module, exports, require) {`,
            result.code,
            '});',
        ].join('\n'));
    }

    const exportNames = Array.from(new Set(entryExports)).filter((name) => name !== 'default').sort();
    const publicConstants = exportNames
        .map((name) => `const ${name} = __igsEntry[${JSON.stringify(name)}];`)
        .join('\n');
    const publicExport = exportNames.length ? `export { ${exportNames.join(', ')} };\n` : '';

    return [
        '// Generated by app/scripts/build.js. Do not edit this file directly.',
        `// IGS version: ${packageJson.version}`,
        'const __igsModules = new Map();',
        'const __igsCache = new Map();',
        'function __igsRegister(id, factory) { __igsModules.set(id, factory); }',
        'function __igsDefine(target, name, getter) { Object.defineProperty(target, name, { enumerable: true, get: getter }); }',
        'function __igsReExport(target, source, pairs) { for (const pair of pairs) __igsDefine(target, pair[1], () => source[pair[0]]); }',
        'function __igsRequire(id) {',
        '    if (__igsCache.has(id)) return __igsCache.get(id).exports;',
        '    const factory = __igsModules.get(id);',
        '    if (!factory) throw new Error(`IGS module not found: ${id}`);',
        '    const module = { exports: {} };',
        '    __igsCache.set(id, module);',
        '    factory(module, module.exports, __igsRequire);',
        '    return module.exports;',
        '}',
        ...transformed,
        `const __igsEntry = __igsRequire(${JSON.stringify(entryId)});`,
        publicConstants,
        'const __igsGlobalObject = globalThis.window || globalThis;',
        'if (__igsGlobalObject && __igsGlobalObject.IGS_AUTO_BOOTSTRAP !== false && !__igsGlobalObject.IGS && typeof bootstrapIGS === "function") {',
        '    bootstrapIGS({ global: __igsGlobalObject });',
        '}',
        publicExport + 'export default __igsEntry;',
        '',
    ].join('\n');
}

function transformModule(module) {
    const exportNames = [];
    const localExportNames = [];
    let importCounter = 0;
    let code = module.source;

    code = code.replace(/^\s*import\s+([\s\S]*?)\s+from\s+['"]([^'"]+)['"];\s*$/gm, (_match, clause, request) => {
        const resolved = resolveLocalModule(module.file, request);
        return renderImportClause(clause, resolved.id);
    });

    code = code.replace(/^\s*export\s+\{([\s\S]*?)\}\s+from\s+['"]([^'"]+)['"];\s*$/gm, (_match, specifierText, request) => {
        const resolved = resolveLocalModule(module.file, request);
        const pairs = parseSpecifierPairs(specifierText);
        for (const pair of pairs) exportNames.push(pair.exported);
        importCounter += 1;
        return `const __igsReExportSource${importCounter} = require(${JSON.stringify(resolved.id)});\n__igsReExport(exports, __igsReExportSource${importCounter}, ${JSON.stringify(pairs.map((pair) => [pair.imported, pair.exported]))});`;
    });

    code = code.replace(/^\s*export\s+(async\s+function|function|class)\s+([A-Za-z_$][\w$]*)/gm, (_match, kind, name) => {
        exportNames.push(name);
        localExportNames.push(name);
        return `${kind} ${name}`;
    });

    code = code.replace(/^\s*export\s+(const|let|var)\s+([A-Za-z_$][\w$]*)/gm, (_match, kind, name) => {
        exportNames.push(name);
        localExportNames.push(name);
        return `${kind} ${name}`;
    });

    code = code.replace(/^\s*export\s+\{([\s\S]*?)\};\s*$/gm, (_match, specifierText) => {
        const pairs = parseSpecifierPairs(specifierText);
        for (const pair of pairs) exportNames.push(pair.exported);
        return pairs.map((pair) => `__igsDefine(exports, ${JSON.stringify(pair.exported)}, () => ${pair.imported});`).join('\n');
    });

    const localExports = Array.from(new Set(localExportNames));
    if (localExports.length) {
        code += `\n${localExports.map((name) => `__igsDefine(exports, ${JSON.stringify(name)}, () => ${name});`).join('\n')}`;
    }

    if (/^\s*(import|export)\s/m.test(code)) {
        throw new Error(`Unsupported module syntax remains in ${path.relative(appRoot, module.file)}`);
    }

    return { code, exportNames: Array.from(new Set(exportNames)) };
}

function renderImportClause(clause, targetId) {
    const normalized = String(clause || '').trim();
    if (!normalized) return `require(${JSON.stringify(targetId)});`;
    if (normalized.startsWith('{')) {
        return `const { ${renderDestructuring(parseSpecifierPairs(normalized.slice(1, -1)))} } = require(${JSON.stringify(targetId)});`;
    }
    if (normalized.startsWith('* as ')) {
        const name = normalized.slice(5).trim();
        return `const ${name} = require(${JSON.stringify(targetId)});`;
    }
    const commaIndex = normalized.indexOf(',');
    if (commaIndex >= 0) {
        const defaultName = normalized.slice(0, commaIndex).trim();
        const namedClause = normalized.slice(commaIndex + 1).trim();
        const lines = [`const ${defaultName} = require(${JSON.stringify(targetId)}).default;`];
        if (namedClause.startsWith('{')) {
            lines.push(`const { ${renderDestructuring(parseSpecifierPairs(namedClause.slice(1, -1)))} } = require(${JSON.stringify(targetId)});`);
        }
        return lines.join('\n');
    }
    return `const ${normalized} = require(${JSON.stringify(targetId)}).default;`;
}

function renderDestructuring(pairs) {
    return pairs.map((pair) => pair.imported === pair.exported ? pair.imported : `${pair.imported}: ${pair.exported}`).join(', ');
}

function parseSpecifierPairs(text) {
    return String(text || '')
        .split(',')
        .map((part) => part.trim())
        .filter(Boolean)
        .map((part) => {
            const pieces = part.split(/\s+as\s+/);
            const imported = pieces[0].trim();
            const exported = (pieces[1] || pieces[0]).trim();
            return { imported, exported };
        });
}

function extractDependencies(source) {
    const dependencies = [];
    collect(/^\s*import\s+[\s\S]*?\s+from\s+['"]([^'"]+)['"];\s*$/gm);
    collect(/^\s*export\s+\{[\s\S]*?\}\s+from\s+['"]([^'"]+)['"];\s*$/gm);
    return dependencies;

    function collect(regex) {
        let match = regex.exec(source);
        while (match) {
            dependencies.push(match[1]);
            match = regex.exec(source);
        }
    }
}

function resolveLocalModule(fromFile, request) {
    if (!request.startsWith('.')) {
        throw new Error(`Build does not support external dependency ${request} in ${path.relative(appRoot, fromFile)}`);
    }
    const resolved = path.resolve(path.dirname(fromFile), request);
    if (!resolved.startsWith(srcRoot)) {
        throw new Error(`Build dependency escapes src/: ${request} in ${path.relative(appRoot, fromFile)}`);
    }
    return { file: resolved, id: moduleId(resolved) };
}

function moduleId(file) {
    return path.relative(appRoot, file).replace(/\\/g, '/');
}
